// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ_hopin_web_api_key_placeholder',
    appId: '1:123456789:web:hopin_web_app_id_placeholder',
    messagingSenderId: '123456789',
    projectId: 'hopin-dev',
    authDomain: 'hopin-dev.firebaseapp.com',
    storageBucket: 'hopin-dev.appspot.com',
    measurementId: 'G-MEASUREMENT_ID_PLACEHOLDER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ_hopin_android_api_key_placeholder',
    appId: '1:123456789:android:hopin_android_app_id_placeholder',
    messagingSenderId: '123456789',
    projectId: 'hopin-dev',
    storageBucket: 'hopin-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ_hopin_ios_api_key_placeholder',
    appId: '1:123456789:ios:hopin_ios_app_id_placeholder',
    messagingSenderId: '123456789',
    projectId: 'hopin-dev',
    storageBucket: 'hopin-dev.appspot.com',
    iosBundleId: 'com.hopin.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ_hopin_macos_api_key_placeholder',
    appId: '1:123456789:ios:hopin_macos_app_id_placeholder',
    messagingSenderId: '123456789',
    projectId: 'hopin-dev',
    storageBucket: 'hopin-dev.appspot.com',
    iosBundleId: 'com.hopin.app',
  );
}